LiskHQ/across-relayer

- scripts/runMainnet.sh
> Min fee config

- scripts/runMainnet.sh
This PR resolves #16 
To be reverted in https://github.com/LiskHQ/across-relayer/issues/19
> Test fee percent

- scripts/runMainnet.sh
This PR resolves #19 
[🔙 Revert MIN_RELAYER_FEE_PCT value](https://github.com/LiskHQ/across-relayer/commit/37e226aa43b3b7fa8b194712d54e5376e430a3c1)
> Revert MIN_RELAYER_FEE_PCT value

- scripts/runMainnet.sh
This PR resolves #22 
- Add slack config in the secret manager
- Pull slack config from secret manager and set env var
> Add slack hook

- scripts/runMainnet.sh
This PR resolves #24
Add `PRIORITY_FEE_SCALER_1=0.8` for mainnet 
Switch RPC providers priority for mainnet,
`"RPC_PROVIDERS=DRPC,GELATO,TENDERLY"`
`"RPC_PROVIDERS_1=DRPC,TENDERLY"`
> Add priority fee

- scripts/runMainnet.sh
Add rebalance config for LSK and USDT.
> Add rebalance config for LSK and USDT

- scripts/installDependencies.sh
Add nodejs installation steps to check for required version of node
> Install required node version

- scripts/installApplication.sh
- scripts/installDependencies.sh
This PR resolves LISK-944.
File path for `.nvmrc` was fixed when reading this file.
> Fix `.nvmrc` file path

- scripts/installDependencies.sh
This PR resolves LISK-944.
If `NVM_DIR` is not set inside `.bashrc` file, it is added.
> Add NVM path to `.bashrc` file

- scripts/installApplication.sh
- scripts/installDependencies.sh
This PR resolves LISK-944.
NVM path is manually loaded inside `installApplication.sh` script.
> Fix NVM path inside scripts

- scripts/runMainnet.sh
This PR resolves [LISK-964](https://onchaincollective.atlassian.net/browse/LISK-964)
Run `yarn relay --wallet void --address <ADDRESS>`, after setting the above environment variable in `.env` file
```
2024-08-19 09:28:33 [info]: {
"at": "Relayer#run",
"message": "Relayer started 🏃‍♂️",
"config": {
...
"sendingRebalancesEnabled": true,
...
}
```
[LISK-964]: https://onchaincollective.atlassian.net/browse/LISK-964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Enable SEND_REBALANCES

- .github/workflows/fork-sync.yaml
> Add workflow file for fork sync

- .github/workflows/docker.yaml
This PR resolves #LISK-959
Add GHA to build and push docker image to ECR
Check workflow run on GH and ECR repository
> Add GHA to build and push docker image to ECR

- config/mainnet/relayerExternalInventory.json
This PR resolves #LISK-1117
NA
> Update relayer inventory config

- .prettierignore
- docker-compose.yml
- fluentbit_config/fluent-bit.conf
- fluentbit_config/parsers.conf
- scripts/lisk/docker/dev/docker-compose-dev.patch
Add fluentbit setup to send the logs to firehose
> Add fluentbit setup

- config/mainnet/relayerExternalInventory.json
- config/sepolia/relayerExternalInventory.json
- config/sepolia/relayerExternalInventory_WETH_LSK_USDT.json
This PR resolves #LISK-1453
- Synchronized the testnet config values with mainnet
- Added mainnet relayer config
NA (WBTC is not deployed/supported on Sepolia/Lisk Sepolia)
> Add WBTC relayer config

- .github/workflows/branch.yaml
- .github/workflows/pr.yaml
- config/mainnet/relayerExternalInventory.json
- config/sepolia/relayerExternalInventory_WETH_LSK_USDT.json
This PR resolves #LISK-1762
NA
> Update across relayer config

- scripts/lisk/docker/mainnet/containerStart_relayer_1.sh
- scripts/lisk/docker/sepolia/containerStart_relayer_1.sh
This PR resolves #LISK-1841
- Add environment variable to enable profitability debug logs
NA
> Enable profitability debug logs

- config/mainnet/relayerExternalInventory.json
- config/sepolia/relayerExternalInventory_LSK.json
- scripts/lisk/docker/sepolia/sourceCommonEnv.sh
This PR resolves #LISK-1973
- Remove WBTC and USDT support from relayer config
NA
> Update relayer config

- .github/workflows/branch.yaml
- .github/workflows/pr.yaml
- package.json
- scripts/spokepool.ts
- src/clients/ProfitClient.ts
- src/clients/SvmFillerClient.ts
- src/clients/index.ts
- src/common/Constants.ts
- src/dataworker/Dataworker.ts
- src/dataworker/DataworkerClientHelper.ts
- src/dataworker/DataworkerConfig.ts
- src/dataworker/PoolRebalanceUtils.ts
- src/dataworker/README.md
- src/dataworker/index.ts
- src/finalizer/utils/cctp/l1ToL2.ts
- src/relayer/Relayer.ts
- src/relayer/RelayerClientHelper.ts
- src/relayer/RelayerConfig.ts
- src/utils/SDKUtils.ts
- test/Dataworker.proposeRootBundle.ts
- test/Relayer.BasicFill.ts
- test/fixtures/Dataworker.Fixture.ts
- yarn.lock
This PR resolves #[LISK-2380](https://onchaincollective.atlassian.net/browse/LISK-2380)
- Merge upstream changes
- Run GHA test workflows on workflow_call
Dev docker test scripts
[LISK-2380]: https://onchaincollective.atlassian.net/browse/LISK-2380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Merge upstream changes & update GHA workflows

- config/mainnet/relayerExternalInventory.json
Update withdrawExcessPeriod for LSK to `64800`
> Update withdrawExcessPeriod for LSK
